Install script was modified

diff --git a/trunc/install b/trunc/install
--- a/trunc/install
+++ b/trunc/install
@@ -1,25 +1,53 @@
 #!/bin/sh
-echo "starting installing kuzya into system  ...please wait"
 
-mkdir -p /usr/share/kuzya
-mkdir -p /usr/share/kuzya/bin
-mkdir -p /usr/bin
-mkdir -p /usr/doc/kuzya
-mkdir -p /usr/include/kuzya
-mkdir -p /usr/share/kuzya/resources/translations
-echo "needed dirs were made"
+echo -en "Starting installing kuzya into system\t\t\t"
+if [ "$LOGNAME" != "root" ]; then
+	echo "...failed!"
+	echo "You need to be root to run this script"
+	exit 1
+else
+	echo "...please wait!"
+fi
 
-cp -f ./graphics/c/graphics.h /usr/include/kuzya/
-cp -fr ./doc /usr/doc/kuzya
-cp -fr ./profiles /usr/share/kuzya/
-cp -fr ./resources /usr/share/kuzya/
-cp -fr ./src/images /usr/share/kuzya/src/
-cp -fr ./resources/qss /usr/share/kuzya/resources/
-echo "needed files were copied"
+echo -en "Making needed dirs\t\t\t\t\t"
+if mkdir -p /usr/share/kuzya 	>/root/ierror	&&
+mkdir -p /usr/share/kuzya/bin	>/root/ierror	&&
+mkdir -p /usr/bin		>/root/ierror	&&
+mkdir -p /usr/doc/kuzya		>/root/ierror	&&
+mkdir -p /usr/include/kuzya	>/root/ierror	&&
+mkdir -p /usr/share/kuzya/resources/translations; then
+	echo "...ok!"
+else
+	echo "...error!"
+	echo &2
+	cat /root/ierror
+	exit 1
+fi
 
-install -Dpm 755 ../bin/kuzyagraph /usr/share/kuzya/bin/kuzyagraph
-install -Dpm 755 ../bin/kuzya      /usr/bin/kuzya
-install -Dpm 755 ./resources/translations/*.qm /usr/share/%{name}/src/translations
-echo "kuzya was instiled"
+echo -en "Copying needed files\t\t\t\t\t"
+if cp -f ./graphics/c/graphics.h /usr/include/kuzya/	2>/root/ierror	&&
+cp -fr ./doc /usr/doc/kuzya				2>/root/ierror 	&&
+cp -fr ./profiles /usr/share/kuzya/			2>/root/ierror 	&&
+cp -fr ./resources /usr/share/kuzya/			2>/root/ierror 	&&
+cp -fr ./src/images /usr/share/kuzya/src/		2>/root/ierror 	&&
+cp -fr ./resources/qss /usr/share/kuzya/resources/	2>/root/ierror; then
+	echo "...ok!"
+else
+	echo "...error!"
+	cat /root/ierror
+	exit 1
+fi
 
-echo "finished instiling!"
+echo -en "Instiling kuzya into the system\t\t\t\t"
+if install -Dpm 755 ../bin/kuzyagraph /usr/share/kuzya/bin/kuzyagraph			>/root/ierror	&&
+install -Dpm 755 ../bin/kuzya      /usr/bin/kuzya					>/root/ierror  &&
+install -Dpm 755 ./resources/translations/*.qm /usr/share/kuzya/src/translations	>/root/ierror; then
+	echo "...ok!"
+else
+	echo "...error!"
+	cat /root/ierror
+	exit 1
+fi
+
+rm -f /root/ierror
+	echo "Kuzya was successfully installied!"
